### PR TITLE
Made code look more hand-written rather than machine generated

### PR DESCRIPTION
**Pull request by rejunity**
- Changed register usage to match RISC-V ABI manual.
- Use of shorter and more human readable pseudo-instructions.
- Setup stack pointer, useful if someone wants to expand this code and needs a stack.
- Added explanatory comments to help people that are new to RISC-V architecture.

### CODE REVIEW

**Comment by noteed** [comment]
Hi, thanks a lot for the changes, especially with the comments, and "solving" the comment in the README :D This is very appreciated.

**Comment by rejunity** [comment]
Hi, you are welcome :) I found your repo very useful for small RISC-V experiments!
Btw, I am looking at how to run this bare metal example on `sifive_e` machine. Just putting code section at 0x20004000 didn't work so far. I am investigating further.

**Comment by noteed** [comment]
Did you also change the base UART address? Here is the correct value: `0x10013000`, see https://github.com/qemu/qemu/blob/master/hw/riscv/sifive_e.c#L66

I'm curious; what kind of experiments do you do ?

**Comment by noteed** [comment]
I managed to run it on the `sifive_e` QEMU machine: see https://github.com/noteed/riscv-hello-asm/tree/sifive_e (there is a single commit to adapt the code in place).

What do you think would be the best way to add that code to this repository ? Duplicate everything ?

**Comment by rejunity** [comment]
Thanks! I got it running on `sifive_e` too! I had a bit more complex test case that was causing me troubles. It uses stack. and turns out that `0x8000` stack size simply does not fit into `sifive_e` memory :) After reducing stack to `0x1000` - everything works, yay!

Talking about the best way to do it, duplication is one way, but actually as we need to change just 2 constants, we could just pass them through the command line to gcc/as/linker. Something like this:
`gcc -Thello.ld hello.s -Wa,--defsym,UART=0x10013000 -Wl,--defsym,ROM_START=0x20400000 -o hello_sifive_e`

I almost have it working. Will send PR in a moment. Check, if you like it.

**Comment by noteed** [comment]
FTR the PR mentioned above is now at https://github.com/noteed/riscv-hello-asm/pull/4

**Pull request merged**
