### PR TITLE
Support for sifive_e machine

### PR DESCRIPTION
**Pull request by rejunity**

### CODE REVIEW

**Comment by noteed** [comment]
Thanks a lot! I think this is much easier to understand that way.

I was wondering if it is possible to reduce the difference in `$ diff -u -r sifive_e/ sifive_u/`; I'll have a try.

**Comment by rejunity** [comment]
You could go almost with the copy of the sifive_e/hello.ld -> sifive_u/hello.ld. I think stack size of 0x1000 is good enough for both for the purposes of example code. Just different ROM/RAM address.

NOTE: I noticed that OUTPUT_FORMAT("elf64-littleriscv") or OUTPUT_FORMAT("elf32-littleriscv") are actually not necessary. It is enough to specify 32/64 in gcc command line arguments and RISC-V is always little-endian.

sifive_u/hello.ld to match sifive_e/hello.ld better:
```
OUTPUT_ARCH( "riscv" )
ENTRY( _start )
SECTIONS
{
  /* text: test code section */
  . = 0x80000000;
  .text : { *(.text) }
  /* gnu_build_id: readonly build identifier */
  .gnu_build_id : { *(.note.gnu.build-id) }
  /* rodata: readonly data segment */
  .rodata : { *(.rodata) }

  /* data: Initialized data segment */
  .data : { *(.data) }
  .sdata : { *(.sdata) }
  .debug : { *(.debug) }
  . += 0x1000;
  stack_top = .;

  /* End of uninitalized data segement */
  _end = .;
}
```

**Comment by rejunity** [comment]
Answering your earlier question:
> I'm curious; what kind of experiments do you do ?

Me and friend are experimenting with code generation. Writing simple compiler from scratch. Plan to do a very bare bones OS for learning purposes.

Btw, I wrote a [minimalistic C-like printf function in RISC-V assembly here](https://github.com/rtfb/riscv64-in-qemu/blob/master/baremetal-print.s). Supports `%s, %c, %d, %i, %u, %x, %o, %p` formatting arguments. Could be handy for small things like the original riscv-probe repo.

**Comment by noteed** [comment]
Interesting. Here I'd like to start with something like https://github.com/nornagon/jonesforth/blob/master/jonesforth.S, and maybe bootstrap an interpreter for a Haskell-like language (maybe following https://github.com/blynn/compiler). But I'm not sure I'll have ever enough time to do that (I'm bad at assembly).

**Pull request merged**
