### PR TITLE
Support for sifive_e machine

### PR DESCRIPTION
**Pull request by rejunity**
Build can be configured using external toolchain arguments such as:
- -Wa,--defsym,UART=0x10013000 and
- -Wl,--defsym,ROM_START=0x20400000

### CODE REVIEW

**Comment by noteed** [comment]
Thanks! I'm wondering if this could be improved:

- I think the `DEFINED()` macros are hard to understand because they depend on each others. I'm wondering if it is possible to use something similar to this directory https://github.com/michaeljclark/riscv-probe/tree/master/env/qemu-sifive_e and the sifive_u sibling. Maybe use a `.inc` file ? Having a file or two that "describe" a machine, instead of relying on the correct `--defsym` passed on the commadn-line seems clearer to me.
- Related to the previous point, those `ifdef` and `DEFINED` won't "scale" very well to additional cases. For instance in my own attempt here https://github.com/noteed/riscv-hello-asm/commit/db0429b9b9921b8b401226ac8ba2e4bf95fbd90c I have used the `elf32-littleriscv` output format.
- Can you rebase your branch (or simply sqash it as a single commit) ? I try to avoid commits such as `Merge branch 'main' into main`.

**Comment by rejunity** [comment]
* LINKER. Yeah, I agree that macros made linker script considerably harder to read which is not great for "bare minimal" code. Plus as you point out, it can't handle `elf32-littleriscv`. Given all that, I guess, more common approach of separate .ld script per machine is better. I will do that.
* ASSEMBLER. Initially I wanted to use include too, but it has side effect of requiring separate directory per machine like: `sifive_e/cfg.inc` and `sifive_u/cfg.inc`. Do you mind such file structure?
* rebase - yes, will do.

**Comment by noteed** [comment]
This sounds very good to me.

**Comment by noteed** [comment]
This PR is thus replaced by https://github.com/noteed/riscv-hello-asm/pull/5.

**Pull request closed without merging**
